### ISSUE TITLE
在setAdapter()之前，如果数据的条数为0，会报空指针导致闪退

### ISSUE THREAD

**Issue by slgluo** [z3896823/PanelList#3]
```
E/AndroidRuntime: FATAL EXCEPTION: main
                  Process: com.zhd.surveytool, PID: 3799
                  java.lang.NullPointerException: Attempt to invoke virtual method 'int android.widget.LinearLayout.getHeight()' on a null object reference
                      at sysu.zyb.panellistlibrary.PanelListAdapter.initColumnLayout(PanelListAdapter.java:406)
                      at sysu.zyb.panellistlibrary.PanelListAdapter.access$500(PanelListAdapter.java:40)
                      at sysu.zyb.panellistlibrary.PanelListAdapter$1.run(PanelListAdapter.java:396)
                      at android.os.Handler.handleCallback(Handler.java:815)
                      at android.os.Handler.dispatchMessage(Handler.java:104)
                      at android.os.Looper.loop(Looper.java:194)
                      at android.app.ActivityThread.main(ActivityThread.java:5877)
                      at java.lang.reflect.Method.invoke(Native Method)
                      at java.lang.reflect.Method.invoke(Method.java:372)
                      at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1019)
                      at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:814)
```

**Comment by z3896823** [comment]
对，如果中间没数据的话，会导致找不到中间ListView的子布局，进而报空指针.现在的新版本在使用方式上杜绝了这种问题的发生，请参考目前最新的README，感谢关注。
